version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: patinda/foodgram_backend
    env_file: .env
    volumes:
      - static_backend:/app/static/
      - media:/app/media/

  frontend:
    image: patinda/foodgram_frontend
    env_file: .env
    volumes:
      - static_frontend:/app/result_build/build

  gateway:
    image: patinda/foodgram_gateway
    ports:
      - '8000:80'
    volumes:
      - static_frontend:/usr/share/nginx/html/
      - static_backend:/app/var/html/static/
      - media:/app/var/html/media/

volumes:
  pg_data:
  static_backend:
  static_frontend:
  media:
