version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: patinda/foodgram_backend
    env_file: .env
    volumes:
      - static_backend:/app/static/
      - media:/app/media/

  frontend:
    image: patinda/foodgram_frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: nginx:1.19.3
    ports:
      - '8000:80'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static_backend:/var/html/static/
      - media:/var/html/media/

volumes:
  pg_data:
  static_backend:
  media:
