# Generated by Django 4.2.3 on 2023-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.PositiveIntegerField(help_text='Введите количество', null=True, verbose_name='количество'),
        ),
    ]
