# Generated by Django 4.2.3 on 2023-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientsrecipes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
