# Generated by Django 4.2.3 on 2023-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_options_alter_ingredients_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=200, unique=True, verbose_name='название'),
        ),
    ]
