# Generated by Django 4.2.3 on 2023-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.IntegerField(default=1, help_text='Введите количество', verbose_name='количество'),
            preserve_default=False,
        ),
    ]
