# Generated by Django 4.2.3 on 2023-07-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipes', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipes', to='recipes.recipes'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
